openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      properties:
        Message:
          type: string
    GetAllProducts:
      properties:
        Products:
          type: array
    GetProductById:
      properties:
        Product:
          type: object
          properties:
            count:
              type: number
            description:
              type: string
            id:
              type: string
            price:
              type: number
            title:
              type: string
  securitySchemes: {}
info:
  title: Product Service API
  description: Product Service API
  version: '1'
paths:
  /products:
    get:
      operationId: getAllProducts
      summary: Get products
      description: Get products
      responses:
        '200':
          description: Products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllProducts'
        '404':
          description: Products not found error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internall server error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/products/{productId}':
    get:
      operationId: getProductById
      summary: Get product by id
      description: Get product by id
      responses:
        '200':
          description: Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductById'
        '404':
          description: Product not found error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internall server error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
