service: product-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: serverless
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

environment:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          method: get
          path: products
          cors:
            origin: "https://dm9otfstrcg58.cloudfront.net"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: products/{productId}
          cors:
            origin: "https://dm9otfstrcg58.cloudfront.net"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              paths:
                productId: true
