service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: serverless
  apiGateway: 
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

environment:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
     - http:
         method: get
         path: products
  getProductById:
    handler: handler.getProductById
    events:
     - http:
         method: get
         path: products/{productId}
         request:
            parameters:
              paths:
                productId: true
